[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'fuenor/qfixgrep'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cespare/vim-toml'


