[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
build = 'make'
hook_add = '''
  let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
  let g:deoplete#sources#go#sort_class = ['var', 'package', 'func', 'type', 'const']
  " let g:deoplete#sources#go#use_cache = 1
  " let g:deoplete#sources#go#json_directory = $HOME.'/.cache/deoplete/go/'
  let g:deoplete#sources#go#package_dot = 1
'''
