[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  " vim-devicons
  let g:webdevicons_conceal_nerdtree_brackets = 1
  let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '

  " dir-icons
  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
  let g:DevIconsEnableFoldersOpenClose = 1
  let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
  let g:DevIconsDefaultFolderOpenSymbol = ''

  " file-icons
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['html'] = ''
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['css'] = ''
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['md'] = ''
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['txt'] = ''
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <silent> <Space>f :<C-u>NERDTree<CR>
  nnoremap <silent> <Space>c :<C-u>NERDTreeClose<CR>

  let g:NERDTreeQuitOnOpen=1
'''

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
hook_add = '''
  let g:NERDTreeFileExtensionHighlightFullName = 1
  let g:NERDTreeExactMatchHighlightFullName = 1
  let g:NERDTreePatternMatchHighlightFullName = 1
'''

# depends unite {{{
[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-filetype'

[[plugins]]
repo = 'Shougo/unite-help'
on_source = 'unite.vim'
# }}}

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = '''
  map /  <Plug>(incsearch-forward)
  map ?  <Plug>(incsearch-backward)
  map g/ <Plug>(incsearch-stay)
'''

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'daisuzu/translategoogle.vim'

# color {{{
[[plugins]]
repo = 'keith/tmux.vim'

[[plugins]]
repo = 'elubow/cql-vim'
# }}}

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_post_source = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'kana/vim-smartinput'
hook_post_source = 'source ~/.vim/rc/plugins/smartinput.rc.vim'

[[plugins]]
repo = 'vim-scripts/Align'
hook_add ='''
  let g:Align_xstrlen = 3
'''

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-template'
hook_add = '''
  autocmd MyAutoCmd User plugin-template-loaded call s:template_keywords()
  function! s:template_keywords()
    silent! %s/<+DATE+>/\=strftime('%Y-%m-%d')/g
    silent! %s/<+FILENAME+>/\=expand('%:r')/g
  endfunction

  autocmd MyAutoCmd User plugin-template-loaded
        \   if search('<+CURSOR+>')
        \ |   silent! execute 'normal! "_da>'
        \ | endif
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  source ~/.vim/rc/plugins/quickrun.rc.vim
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add ='''
  let g:memolist_path = "~/Documents/Memo"
  let g:memolist_memo_suffix = "md"
  let g:memolist_memo_date = "%Y-%m-%d %H:%M"
  let g:memolist_memo_date = "epoch"
  let g:memolist_memo_date = "%D %T"
  let g:memolist_prompt_tags = 1
  let g:memolist_prompt_categories = 1
  let g:memolist_qfixgrep = 1
  let g:memolist_ex_cmd = "NERDTree"
  let g:memolist_template_dir_path = "~/.vim/template/memolist"

  map <Space>mn  :MemoNew<CR>
  map <Space>ml  :MemoList<CR>
  map <Space>mg  :MemoGrep<CR>
'''

[[plugins]]
repo = 'fuenor/qfixgrep'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  " let g:gitgutter_sign_added = '+'
  " let g:gitgutter_sign_modified = '>'
  " let g:gitgutter_sign_removed = '-'
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  nnoremap <silent> <Space>2 :<C-u>TagbarToggle<CR>
  let g:tagbar_autofocus = 1
  let g:tagbar_type_go = {
      \ 'ctagstype' : 'go',
      \ 'kinds'     : [
          \ 'p:package',
          \ 'i:imports:1',
          \ 'c:constants',
          \ 'v:variables',
          \ 't:types',
          \ 'n:interfaces',
          \ 'w:fields',
          \ 'e:embedded',
          \ 'm:methods',
          \ 'r:constructor',
          \ 'f:functions'
      \ ],
      \ 'sro' : '.',
      \ 'kind2scope' : {
          \ 't' : 'ctype',
          \ 'n' : 'ntype'
      \ },
      \ 'scope2kind' : {
          \ 'ctype' : 't',
          \ 'ntype' : 'n'
      \ },
      \ 'ctagsbin'  : 'gotags',
      \ 'ctagsargs' : '-sort -silent'
  \ }
'''

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = '''
  let g:auto_ctags = 1
  let g:auto_ctags_tags_args = '--tag-relative --recurse'
  let g:auto_ctags_directory_list = ['.git', '.svn', '$HOME/.ctags.d']
  set tags+=.git/tags
  set tags+=.svn/tags
  set tags+=$HOME/.ctags.d/tags
'''

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add = '''
  nnoremap <silent> ,m :OverCommandLine<CR>
'''

[[plugins]]
repo = 'haya14busa/vim-asterisk'
hook_add = '''
  map *   <Plug>(asterisk-*)
  map #   <Plug>(asterisk-#)
  map g*  <Plug>(asterisk-g*)
  map g#  <Plug>(asterisk-g#)
  map z*  <Plug>(asterisk-z*)
  map gz* <Plug>(asterisk-gz*)
  map z#  <Plug>(asterisk-z#)
  map gz# <Plug>(asterisk-gz#)

  let g:asterisk#keeppos = 1
'''

[[plugins]]
repo = 'haya14busa/vim-edgemotion'
hook_add = '''
  map <C-j> <Plug>(edgemotion-j)
  map <C-k> <Plug>(edgemotion-k)
'''
