# Unite
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
[[plugins]]
repo = 'Shougo/neomru.vim'
on_event = ['BufEnter']
[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = {n = '<Plug>'}
on_if = "isdirectory(bufname('%'))"
hook_add = 'nnoremap <silent> <Space>f :<C-u>VimFiler -invisible<CR>'

# Auto complete
[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/rc/plugins/neocomplete.rc.vim
'''
[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source ~/.vim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Konfekt/FastFold'
on_event = ['BufEnter']
hook_post_source = 'FastFoldUpdate'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
on_event = ['BufEnter']

# Filetype

# Python
[[plugins]]
repo = 'davidhalter/jedi-vim'
if = '!has("neovim")'
on_ft = ['python']
on_source = '~/.vim/rc/plugins/jedi-vim.vim'

[[plugins]]
repo =  'hynek/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = ['python']
on_source = 'source ~/.vim/rc/plugins/jedi-vim.rc.vim'

# Golang
[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = ['go']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

# Markdown
[[plugins]]
repo = 'nelstrom/vim-markdown-folding'
on_ft = ['markdown']

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown']
