---
version: 2

root-markers:
  - .git/

# log-file: /Users/nametake/Downloads/output.log
# log-level: 1

tools:
  json-jq: &json-jq
    lint-command: 'jq .'

  json-fixjson: &json-fixjson
    format-command: 'fixjson'

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

languages:
  json:
    - <<: *json-jq
    - <<: *json-fixjson
  yaml:
    - <<: *yaml-yamllint
