---
version: 2

root-markers:
  - .git/

# log-file: /Users/nametake/Downloads/output.log
# log-level: 1

tools:
  apex-pmd: &apex-pmd
    lint-command: 'pmd pmd -format textpad -rulesets apex-quickstart -d ${INPUT}'
    lint-formats:
      - '%f(%l, %r):  %m'

  css-stylelint: &css-stylelint
    lint-command: './node_modules/.bin/stylelint --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: false
    lint-stdin: true
    lint-formats:
      - '%-P%f'
      - '%*[\ ]%l:%c%*[\ ]%*[✖⚠]%*[\ ]%m'
      - '%-Q'

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint'
    lint-formats:
      - '%f:%l %m'

  javascript-eslint: &javascript-eslint
    lint-command: './node_modules/.bin/eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    commands:
      - title: 'eslint fix'
        command: ./node_modules/.bin/eslint
        arguments:
          - '--fix'
          - '${INPUT}'

  javascript-prettier: &javascript-prettier
    format-command: './node_modules/.bin/prettier --stdin-filepath ${INPUT}'
    format-stdin: true

  json-jq: &json-jq
    lint-command: 'jq .'

  json-fixjson: &json-fixjson
    format-command: 'fixjson'
    format-stdin: true

  json-jq-format: &json-jq-format
    format-command: 'jq . --sort-keys'
    format-stdin: true

  markdown-remark-format: &markdown-remark-format
    format-command: 'remark --no-color --silent'
    format-stdin: true

  markdown-remark-lint: &markdown-remark-lint
    lint-command: 'remark --no-stdout --no-color --frail'
    lint-formats:
      - '%-P%f'
      - '%#%l:%c %# %trror  %m'
      - '%#%l:%c %# %tarning  %m'
      - '%-Q'
      - '%-G%.%#'

  markdown-textlint: &markdown-textlint
    lint-command: 'textlint --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-formats:
      - '%-P%f'
      - '%#%l:%c %# %trror  %m'
      - '%#%l:%c %# %tarning  %m'
      - '%-Q'
      - '%-G%.%#'

  proto-buf: &proto-buf
    lint-command: 'buf check lint --file ${INPUT}'
    lint-formats:
      - '%f:%l:%c:%m'

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

frontend: &frontend
  - <<: *css-stylelint
  - <<: *javascript-eslint
  - <<: *javascript-prettier

languages:
  apex:
    - <<: *apex-pmd
  dockerfile:
    - <<: *dockerfile-hadolint
  json:
    - <<: *json-jq
    - <<: *json-fixjson
    # - <<: *json-jq-format
  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt
  javascript: *frontend
  javascriptreact: *frontend
  markdown:
    - <<: *markdown-remark-lint
    - <<: *markdown-remark-format
    - <<: *markdown-textlint
  proto:
    - <<: *proto-buf
  typescript: *frontend
  typescriptreact: *frontend
  yaml:
    - <<: *yaml-yamllint
  vim:
    - <<: *vim-vint
