---
version: 2

root-markers:
  - .git/

# log-file: /Users/nametake/Downloads/output.log
# log-level: 1

tools:
  json-jq: &json-jq
    lint-command: 'jq .'

  json-fixjson: &json-fixjson
    format-command: 'fixjson'
    format-stdin: true

  json-jq-format: &json-jq-format
    format-command: 'jq . --sort-keys'
    format-stdin: true

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

languages:
  json:
    - <<: *json-jq
    - <<: *json-fixjson
    - <<: *json-jq-format
  yaml:
    - <<: *yaml-yamllint
  vim:
    - <<: *vim-vint
