---
version: 2

tools:
  golangci-lint: &golangci-lint
    lint-command: 'golangci-lint run --enable-all'

  gofmtrlx: &gofmtrlx
    format-command: 'gofmtrlx -s -w'

  json-jq: &json-jq
    lint-command: 'jq .'

  json-fixjson: &json-fixjson
    format-command: 'fixjson'

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

languages:
  go:
    - <<: *golangci-lint
    - <<: *gofmtrlx
  json:
    - <<: *json-jq
    - <<: *json-fixjson
  yaml:
    - <<: *yaml-yamllint
