---
version: 2

root-markers:
  - .git/

log-file: /Users/nametake/Downloads/output.log
log-level: 1

tools:
  css-stylelint: &css-stylelint
    lint-command: './node_modules/.bin/stylelint --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: false
    lint-stdin: true
    lint-formats:
      - '%-P%f'
      - '%*[\ ]%l:%c%*[\ ]%*[✖⚠]%*[\ ]%m'
      - '%-Q'

  javascript-eslint: &javascript-eslint
    lint-command: './node_modules/.bin/eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  javascript-prettier: &javascript-prettier
    format-command: './node_modules/.bin/prettier --stdin-filepath ${INPUT}'
    format-stdin: true

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint'
    lint-formats:
      - '%f:%l %m'

  json-jq: &json-jq
    lint-command: 'jq .'

  json-fixjson: &json-fixjson
    format-command: 'fixjson'
    format-stdin: true

  json-jq-format: &json-jq-format
    format-command: 'jq . --sort-keys'
    format-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

frontend: &frontend
  - <<: *css-stylelint
  - <<: *javascript-eslint
  - <<: *javascript-prettier

languages:
  dockerfile:
    # - <<: *docker-hadolint # TODO M1 support
  json:
    - <<: *json-jq
    - <<: *json-fixjson
    - <<: *json-jq-format
  sh:
    # - <<: *sh-shellcheck # TODO M1 support
    - <<: *sh-shfmt
  javascript: *frontend
  javascriptreact: *frontend
  typescript: *frontend
  typescriptreact: *frontend
  yaml:
    - <<: *yaml-yamllint
  vim:
    - <<: *vim-vint
